# netlify.toml

# Build settings
[build]
  command = "npm run build" # The command to build your site
  publish = "dist"          # The directory to publish

# Redirect and rewrite rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200